bucket         = "terraform-remote-backend-shared-services-dev"
key            = "ag-spa-starter/state.tfstate"
region         = "eu-west-1"
encrypt        = "true"
dynamodb_table = "terraform_state_lock"
